import { LegalPage, LegalSection } from '@/components/legal-site';

export const metadata = { title: 'Terms of Service' };
export default function TermsPage(){return <LegalPage eyebrow="Effective 31 August 2026" title="Terms of Service" summary="The rules governing access to RestaurantMS, its staff workspaces, customer ordering surfaces, and related services.">
  <LegalSection title="1. Agreement and eligibility"><p>These Terms form an agreement between the organization identified in the applicable order form or account record (“Customer”) and the legal entity operating RestaurantMS (“RestaurantMS,” “we,” or “us”). A person accepting these Terms represents that they have authority to bind the Customer and are legally capable of entering the agreement.</p></LegalSection>
  <LegalSection title="2. The service"><p>RestaurantMS provides hosted restaurant-management software, including point of sale, ordering, kitchen display, inventory, staff access, analytics, and configurable modules. Features may vary by plan, tenant configuration, branch, and integration availability.</p><p>RestaurantMS is not a bank, card network, money-transfer operator, merchant acquirer, or payment institution. Payment references and proof images may be displayed for restaurant verification, but the restaurant remains responsible for confirming receipt, refunds, taxes, receipts, and compliance with payment-provider terms.</p></LegalSection>
  <LegalSection title="3. Accounts and access"><p>Customers must provide accurate account information, restrict accounts to authorized users, assign roles appropriately, and promptly revoke access that is no longer required. Credentials may not be shared. Customers are responsible for activity performed through their accounts except to the extent caused by RestaurantMS.</p></LegalSection>
  <LegalSection title="4. Acceptable use"><p>Users must not use the service to violate law; infringe intellectual-property or privacy rights; process unlawful, deceptive, discriminatory, or harmful content; interfere with service integrity; probe or bypass security; introduce malicious code; scrape or resell the service without permission; impersonate another person; or use payment-proof workflows to facilitate fraud.</p></LegalSection>
  <LegalSection title="5. Customer data"><p>As between the parties, the Customer retains its rights in menu, employee, order, customer, inventory, and other data submitted to the service. The Customer authorizes RestaurantMS to host, process, transmit, back up, and display that data as necessary to provide, secure, support, and improve the contracted service.</p><p>The Customer is responsible for providing required notices, choosing a lawful basis, honoring customer rights, and avoiding collection of information that is unnecessary for restaurant operations.</p></LegalSection>
  <LegalSection title="6. Fees, suspension, and termination"><p>Commercial fees, taxes, renewal, trials, and payment dates will be stated in the applicable order form. We may suspend access for material security risk, unlawful use, non-payment, or material breach after reasonable notice when circumstances permit. Either party may terminate as provided in its order form or for uncured material breach.</p></LegalSection>
  <LegalSection title="7. Intellectual property"><p>RestaurantMS and its licensors retain all rights in the software, interfaces, documentation, trademarks, and improvements. No rights are granted except the limited, non-exclusive, non-transferable right to use the service during the subscription. Feedback may be used without restriction or attribution.</p></LegalSection>
  <LegalSection title="8. Availability and warranties"><p>The service is provided using reasonable care and skill. Except for warranties that cannot legally be excluded, the service is provided “as is” and “as available.” We do not guarantee uninterrupted operation, error-free results, particular revenue outcomes, or continuous availability of third-party networks, devices, or payment providers.</p></LegalSection>
  <LegalSection title="9. Liability"><p>To the maximum extent permitted by applicable law, neither party is liable for indirect, incidental, special, punitive, or consequential loss, including lost profit or lost data. Any aggregate liability cap, exclusions, and exceptions for confidentiality, data protection, fraud, gross negligence, or willful misconduct must be stated in the final commercial agreement and applied only where lawful.</p></LegalSection>
  <LegalSection title="10. Law, changes, and contact"><p>The governing law, courts or arbitration forum, contracting entity, and formal notice address will be specified before commercial launch. Material changes will be announced through the service or an account contact and will take effect prospectively. Questions may be directed through the account administrator until formal legal contact details are published.</p></LegalSection>
</LegalPage>}
