import { LegalPage, LegalSection } from '@/components/legal-site';

export const metadata = { title: 'Privacy Notice' };
export default function PrivacyPage(){return <LegalPage eyebrow="Effective 31 August 2026" title="Privacy Notice" summary="How RestaurantMS handles personal data across its website, restaurant workspaces, customer ordering flows, and support operations.">
  <LegalSection title="1. Scope and roles"><p>This notice applies to RestaurantMS website visitors, account administrators, staff users, and people who interact with customer-ordering pages. For restaurant order, employee, and guest data, the restaurant generally determines why and how the information is used and RestaurantMS processes it to provide the service. For account administration, website security, billing, and direct support, RestaurantMS may act as the data controller.</p></LegalSection>
  <LegalSection title="2. Data we handle"><p>Depending on use, we may handle names, contact information, credentials and authentication records, tenant and branch memberships, job roles, device and network information, security logs, orders, table or pickup details, transaction references, payment-proof images, menu preferences, support messages, inventory activity, and audit records.</p><p>Restaurants should not use free-text fields or uploads to collect national identification, financial credentials, health information, or other sensitive personal data unless strictly necessary and lawfully authorized.</p></LegalSection>
  <LegalSection title="3. Why data is used"><p>Data is used to provide and secure accounts; route and fulfill orders; support cashier verification; operate kitchen, table, inventory, and reporting tools; respond to requests; prevent fraud and abuse; maintain auditability; meet legal obligations; and improve reliability and usability.</p></LegalSection>
  <LegalSection title="4. Legal basis and Ethiopian privacy law"><p>Processing is intended to follow applicable law, including Ethiopia’s Personal Data Protection Proclamation No. 1321/2024. Depending on the context, processing may rely on performance of a contract, consent, compliance with law, protection of vital interests, or legitimate interests that do not override individual rights. The responsible restaurant must identify and document the appropriate basis for its processing.</p></LegalSection>
  <LegalSection title="5. Sharing and international processing"><p>Information may be shared with authorized restaurant users, infrastructure and hosting providers, security and support vendors, approved integration providers, professional advisers, and public authorities when legally required. Data may be processed outside Ethiopia only with appropriate contractual, security, and legal safeguards required for cross-border transfer.</p></LegalSection>
  <LegalSection title="6. Retention and security"><p>Information is retained only as long as necessary for the service, restaurant instructions, legitimate operational records, dispute handling, security, and legal obligations. Safeguards may include encryption in transit, access controls, tenant and branch scoping, credential protection, logging, backups, monitoring, and incident-response procedures. No system can guarantee absolute security.</p></LegalSection>
  <LegalSection title="7. Individual rights"><p>Subject to applicable law, individuals may request information about processing and seek access, correction, deletion, restriction, objection, portability, withdrawal of consent, or review of certain automated decisions. Restaurant guests and staff should normally contact the restaurant first. RestaurantMS will assist customers with verified requests where required.</p></LegalSection>
  <LegalSection title="8. Children, changes, and contact"><p>RestaurantMS is designed for restaurant operations and is not directed to children. Restaurants must obtain any required guardian authorization before knowingly collecting a child’s information. Material notice changes will be published here with a revised effective date. Formal controller identity, registered address, data-protection contact, and complaint channel must be published before production launch.</p></LegalSection>
</LegalPage>}
