'use client';
import { useState } from 'react';
import { PageTitle, Panel } from './role-workflows';

export function KitchenWorkflow() {
  const seed=[{id:'#1045',source:'Table 03',age:4,status:'CONFIRMED',items:['2 × Shiro Wot','1 × Injera'],note:'One mild'},{id:'#1048',source:'Table 08',age:12,status:'IN PROGRESS',items:['2 × Special Tibs','1 × Fresh Spris'],note:'No onion on one tibs'},{id:'#1046',source:'Counter',age:18,status:'READY',items:['1 × Beyaynetu','2 × Buna'],note:''}];
  const [tickets,setTickets]=useState(seed); const [recalled,setRecalled]=useState<typeof seed>([]);
  function bump(id:string){const ticket=tickets.find(x=>x.id===id)!;const next=ticket.status==='CONFIRMED'?'IN PROGRESS':ticket.status==='IN PROGRESS'?'READY':'COMPLETED';setTickets(v=>v.filter(x=>x.id!==id).concat(next==='COMPLETED'?[]:[{...ticket,status:next}]));if(next==='COMPLETED')setRecalled(v=>[ticket,...v]);}
  return <><PageTitle label="Kitchen display" title="Live kitchen queue" copy="Prioritize, bump, recall, and track detailed tickets across preparation stations." action={<div className="flex gap-2"><button className="rounded-xl border border-line bg-white px-4 py-3 text-xs font-black">Sound on</button><button onClick={()=>{if(recalled[0])setTickets(v=>[...v,recalled[0]]);setRecalled(v=>v.slice(1))}} className="rounded-xl bg-[#18241f] px-4 py-3 text-xs font-black text-white">Recall last</button></div>}/><div className="grid gap-4 xl:grid-cols-3">{['CONFIRMED','IN PROGRESS','READY'].map(lane=><section key={lane}><div className="mb-3 flex justify-between"><h2 className="text-xs font-black tracking-wider">{lane}</h2><span className="rounded-full bg-white px-2 py-1 text-xs font-black">{tickets.filter(x=>x.status===lane).length}</span></div><div className="space-y-3">{tickets.filter(x=>x.status===lane).map(t=><Panel className={`overflow-hidden ${t.age>15?'border-red-300':''}`} key={t.id}><div className={`flex justify-between p-4 text-white ${t.age>15?'bg-red-700':'bg-[#17231f]'}`}><b className="text-lg">{t.id}</b><span className="text-xs font-black">{t.age} MIN</span></div><div className="p-5"><b>{t.source}</b><div className="mt-4 space-y-2 text-sm">{t.items.map(x=><p key={x}>{x}</p>)}</div>{t.note&&<p className="mt-4 rounded-lg bg-amber-50 p-3 text-xs font-bold text-amber-900">NOTE · {t.note}</p>}<button onClick={()=>bump(t.id)} className="mt-5 w-full rounded-xl bg-brand py-3 text-sm font-black text-white">{lane==='READY'?'Complete':'Bump'} →</button></div></Panel>)}</div></section>)}</div></>;
}

export function InventoryWorkflow() {
  const [modal,setModal]=useState(false); const [adjusted,setAdjusted]=useState(false);
  const stock=[['Beef portions','Batch BF-028','18 / 70','LOW','26 Aug'],['Injera','Batch IN-114','84 / 120','HEALTHY','24 Aug'],['Coffee servings','Batch CF-042','42 / 60','HEALTHY','12 Sep'],['Chicken portions','Batch CH-019','31 / 50','HEALTHY','28 Aug']];
  return <><PageTitle label="Stock control" title="Inventory & batches" copy="Convert bulk receipts into recipe-backed portions, monitor depletion, and audit every adjustment." action={<button onClick={()=>setModal(true)} className="rounded-xl bg-[#18241f] px-5 py-3 text-sm font-black text-white">+ Receive batch</button>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stock.map(x=><Panel className="p-5" key={x[0]}><div className="flex justify-between"><span className="text-xs font-black text-brand">{x[1]}</span><span className={`rounded-full px-2 py-1 text-[9px] font-black ${x[3]==='LOW'?'bg-red-50 text-red-700':'bg-emerald-50 text-emerald-700'}`}>{x[3]}</span></div><h2 className="mt-4 font-black">{x[0]}</h2><p className="mt-2 text-3xl font-black">{adjusted&&x[0]==='Beef portions'?'23 / 70':x[2]}</p><div className="mt-4 h-2 rounded-full bg-muted"><div className="h-full rounded-full bg-brand" style={{width:x[3]==='LOW'?'26%':'70%'}}/></div><p className="mt-3 text-xs text-ink-muted">Expires {x[4]}</p><button onClick={()=>setAdjusted(true)} className="mt-4 text-xs font-black text-brand">Adjust stock →</button></Panel>)}</div><Panel className="mt-5 p-6"><h2 className="text-lg font-black">Consumption audit</h2>{['Order #1048 deducted 2 beef portions','Waste adjustment: 1 injera','Batch CF-042 received: 60 servings'].map((x,i)=><div className="flex justify-between border-b border-line py-4 text-sm" key={x}><b>{x}</b><span className="text-ink-muted">{i+3} min ago</span></div>)}</Panel>{modal&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/45 p-4"><Panel className="w-full max-w-xl p-6"><div className="flex justify-between"><h2 className="text-xl font-black">Receive and portion batch</h2><button onClick={()=>setModal(false)}>×</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><input className="rounded-xl border border-line p-3" placeholder="Ingredient name"/><input className="rounded-xl border border-line p-3" placeholder="Bulk quantity, e.g. 20 kg"/><input className="rounded-xl border border-line p-3" placeholder="Yield, e.g. 70 portions"/><input type="date" className="rounded-xl border border-line p-3"/><textarea className="min-h-20 rounded-xl border border-line p-3 sm:col-span-2" placeholder="Receiving note"/></div><button onClick={()=>setModal(false)} className="mt-5 rounded-xl bg-brand px-5 py-3 text-sm font-black text-white">Create batch</button></Panel></div>}</>;
}

export function SettingsWorkflow() {
  const [saved,setSaved]=useState(false); const [colour,setColour]=useState('#b4532a');
  return <><PageTitle label="Restaurant settings" title="Branding & configuration" copy="Customize the public storefront while keeping the operational interface consistent and accessible." action={<button onClick={()=>setSaved(true)} className="rounded-xl bg-[#18241f] px-5 py-3 text-sm font-black text-white">{saved?'Saved':'Save changes'}</button>}/><div className="grid gap-5 xl:grid-cols-[1fr_.85fr]"><Panel className="p-6"><h2 className="text-lg font-black">Restaurant identity</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-black text-ink-muted">Display name<input defaultValue="Buna House" className="mt-2 w-full rounded-xl border border-line p-3 text-sm"/></label><label className="text-xs font-black text-ink-muted">Primary colour<input type="color" value={colour} onChange={e=>setColour(e.target.value)} className="mt-2 h-12 w-full rounded-xl border border-line p-1"/></label><label className="text-xs font-black text-ink-muted">Corner style<select className="control-select mt-2"><option>Soft</option><option>Rounded</option><option>Square</option></select></label><label className="text-xs font-black text-ink-muted">Storefront mode<select className="control-select mt-2"><option>Warm light</option><option>Dark</option></select></label></div><div className="mt-5 rounded-xl border-2 border-dashed border-line p-6 text-center text-sm font-bold text-ink-muted">Upload logo or cover image</div></Panel><Panel className="overflow-hidden"><div className="p-5 text-white" style={{background:colour}}><p className="text-xs font-bold text-white/70">LIVE PREVIEW</p><h2 className="mt-2 text-2xl font-black">Buna House</h2><p className="mt-1 text-sm text-white/80">Made with warmth. Served with pride.</p></div><div className="p-5"><div className="rounded-xl border border-line p-4"><p className="font-black">Special Tibs</p><p className="mt-1 text-xs text-ink-muted">Tender beef, rosemary and peppers</p><p className="mt-3 font-black" style={{color:colour}}>ETB 400</p></div></div></Panel></div><Panel className="mt-5 p-6"><h2 className="text-lg font-black">Ordering modules</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{['Table QR ordering','Pickup ordering','Kitchen display','Batch inventory'].map(x=><label className="flex items-center justify-between rounded-xl bg-muted p-4 text-sm font-bold" key={x}>{x}<input type="checkbox" defaultChecked className="size-5 accent-[#b4532a]"/></label>)}</div></Panel></>;
}
