'use client';

import { useEffect, useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ApiError, apiRequest, formatEtbMinor, type ApiEnvelope } from '@/lib/api-client';
import { useAuth } from './auth-provider';

interface ShiftProjection { id:string; status:'OPEN'; openingCashMinor:string; approvedCashMinor:string; expectedCashMinor:string; cashOrderCount:number; cashPaymentCount:number; openedAt:string; version:number; }
interface ShiftReport { id:string; cashShiftId:string; openingCashMinor:string; approvedCashMinor:string; expectedCashMinor:string; countedCashMinor:string; varianceMinor:string; varianceReason:string|null; orderCount:number; paymentCount:number; localOpenedAt:string; localClosedAt:string; localBusinessDate:string; }

function etbToMinor(value:string):string|null { const normalized=value.trim().replace(/,/g,''); if(!/^\d{1,14}(?:\.\d{1,2})?$/.test(normalized))return null; const [whole,fraction='']=normalized.split('.'); return (BigInt(whole)*100n+BigInt(fraction.padEnd(2,'0'))).toString(); }

export function CashShiftWorkspace(){
  const {accessToken,csrfToken,profile}=useAuth(); const membership=profile?.memberships[0];
  const branchId=typeof window==='undefined'?'':window.sessionStorage.getItem('rms-branch-id')??membership?.branchAssignments[0]?.branchId??'';
  const tenantId=membership?.tenant.id??''; const [online,setOnline]=useState(true); const [opening,setOpening]=useState(''); const [counted,setCounted]=useState(''); const [reason,setReason]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string|null>(null); const [report,setReport]=useState<ShiftReport|null>(null); const [clock,setClock]=useState(0);
  useEffect(()=>{const update=()=>setOnline(navigator.onLine);update();window.addEventListener('online',update);window.addEventListener('offline',update);const timer=window.setInterval(()=>setClock((value)=>value+1),60_000);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update);window.clearInterval(timer);};},[]);
  const query=useQuery({queryKey:['current-shift',tenantId,branchId],enabled:Boolean(accessToken&&tenantId&&branchId),queryFn:async()=> (await apiRequest<ApiEnvelope<ShiftProjection|null>>(`/branches/${branchId}/shifts/current`,{accessToken,tenantId})).data,refetchInterval:15_000});
  const shift=query.data; const countedMinor=etbToMinor(counted); const variance=shift&&countedMinor!==null?BigInt(countedMinor)-BigInt(shift.expectedCashMinor):null; const elapsed=useMemo(()=>shift?Math.max(0,Math.floor((Date.now()-new Date(shift.openedAt).getTime())/60_000)):0,[shift,clock]);
  async function openShift(event:React.FormEvent){event.preventDefault();const minor=etbToMinor(opening);if(minor===null)return setMessage('Enter opening cash as a valid ETB amount with no more than two decimal places.');if(!online)return setMessage('You are offline. Reconnect before opening a shift.');setBusy(true);setMessage(null);try{await apiRequest(`/branches/${branchId}/shifts/open`,{method:'POST',body:{openingCashMinor:minor},accessToken,csrfToken,tenantId});setOpening('');await query.refetch();}catch(error){setMessage(error instanceof ApiError?error.message:'Could not open the shift.');}finally{setBusy(false);}}
  async function closeShift(event:React.FormEvent){event.preventDefault();if(!shift||countedMinor===null)return setMessage('Enter the counted drawer cash before closing.');if(variance!==0n&&!reason.trim())return setMessage('Explain the non-zero cash variance before closing.');if(!online)return setMessage('You are offline. Reconnect before closing the shift.');setBusy(true);setMessage(null);try{const result=await apiRequest<{shift:ShiftProjection;report:ShiftReport}>(`/branches/${branchId}/shifts/${shift.id}/close`,{method:'POST',body:{countedCashMinor:countedMinor,varianceReason:variance===0n?undefined:reason.trim(),expectedVersion:shift.version},accessToken,csrfToken,tenantId});setReport(result.report);setCounted('');setReason('');await query.refetch();}catch(error){if(error instanceof ApiError&&error.status===409){await query.refetch();setMessage('Another user changed this shift. The latest authoritative totals are shown; review them before retrying.');}else setMessage(error instanceof ApiError?error.message:'Could not close the shift.');}finally{setBusy(false);}}
  if(!membership||!['OWNER','MANAGER','CASHIER'].includes(membership.role))return <State title="Permission denied" detail="This page is available to cash-handling staff only."/>;
  if(query.isLoading)return <State title="Loading shift…" detail="Retrieving the current drawer state."/>;
  if(query.isError)return <State title="Shift unavailable" detail="Reconnect and try again." retry={()=>void query.refetch()}/>;
  if(report)return <Report report={report} onDone={()=>setReport(null)}/>;
  return <><header className="mb-7"><p className="text-xs font-black uppercase tracking-wider text-brand">Cashier shift</p><h1 className="mt-2 text-3xl font-black">{shift?'Current shift':'Open your shift'}</h1><p className="mt-2 text-sm text-ink-muted">{shift?`Open for ${Math.floor(elapsed/60)}h ${elapsed%60}m. Later cash confirmations require a new shift after closure.`:'An active shift is required before confirming cash payments.'}</p></header>{!online&&<div role="status" className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 font-bold text-red-800">Offline — financial actions are disabled until the server reconnects.</div>}{message&&<div role="alert" className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-900">{message}</div>}
  {!shift?<form onSubmit={openShift} className="max-w-xl rounded-2xl border border-line bg-white p-6 shadow-card"><label className="block text-sm font-black">Opening cash (ETB)<input autoFocus inputMode="decimal" value={opening} onChange={(event)=>setOpening(event.target.value)} placeholder="0.00" className="mt-2 min-h-12 w-full rounded-xl border border-line px-4 text-lg tabular-nums"/></label><button disabled={busy||!online} className="mt-5 min-h-12 w-full rounded-xl bg-[#18241f] font-black text-white disabled:opacity-50">{busy?'Opening…':'Open cash shift'}</button></form>:
  <div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Opening cash" value={shift.openingCashMinor}/><Metric label="Confirmed cash" value={shift.approvedCashMinor} detail={`${shift.cashOrderCount} cash orders`}/><Metric label="Expected drawer" value={shift.expectedCashMinor}/><Metric label="Elapsed" text={`${Math.floor(elapsed/60)}h ${elapsed%60}m`} detail={`${shift.cashPaymentCount} approved payments`}/></div><form onSubmit={closeShift} className="mt-5 max-w-3xl rounded-2xl border border-line bg-white p-6 shadow-card"><h2 className="text-xl font-black">Close shift reconciliation</h2><p className="mt-1 text-sm text-ink-muted">Count the physical drawer before entering an amount.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-black">Counted cash (ETB)<input inputMode="decimal" value={counted} onChange={(event)=>setCounted(event.target.value)} placeholder="Leave empty until counted" className="mt-2 min-h-12 w-full rounded-xl border border-line px-4 tabular-nums"/></label><div className="rounded-xl bg-muted p-4"><p className="text-xs font-bold text-ink-muted">Calculated variance</p><p className={`mt-2 text-xl font-black tabular-nums ${variance&&variance!==0n?'text-red-700':''}`}>{variance===null?'—':formatEtbMinor(variance)}</p></div></div>{variance!==null&&variance!==0n&&<label className="mt-4 block text-sm font-black">Variance reason<textarea required maxLength={255} value={reason} onChange={(event)=>setReason(event.target.value)} className="mt-2 min-h-24 w-full rounded-xl border border-line p-3"/></label>}<button disabled={busy||!online||countedMinor===null} className="mt-5 min-h-12 rounded-xl bg-red-700 px-6 font-black text-white disabled:opacity-50">{busy?'Closing…':'Close shift and create report'}</button></form></div>}</>;
}
function Metric({label,value,text,detail}:{label:string;value?:string;text?:string;detail?:string}){return <section className="rounded-2xl border border-line bg-white p-5 shadow-card"><p className="text-sm font-bold text-ink-muted">{label}</p><p className="mt-3 text-2xl font-black tabular-nums">{text??formatEtbMinor(value??'0')}</p>{detail&&<p className="mt-2 text-xs text-ink-muted">{detail}</p>}</section>;}
function Report({report,onDone}:{report:ShiftReport;onDone:()=>void}){function download(){const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`shift-${report.cashShiftId}.json`;link.click();URL.revokeObjectURL(url);}return <section className="rounded-2xl border border-line bg-white p-6 shadow-card"><p className="text-xs font-black uppercase tracking-wider text-emerald-700">Shift closed</p><h1 className="mt-2 text-3xl font-black">Immutable shift report</h1><div className="mt-6 grid gap-3 sm:grid-cols-2"><Metric label="Opening cash" value={report.openingCashMinor}/><Metric label="Confirmed cash" value={report.approvedCashMinor}/><Metric label="Expected drawer" value={report.expectedCashMinor}/><Metric label="Counted cash" value={report.countedCashMinor}/><Metric label="Variance" value={report.varianceMinor}/><Metric label="Cash payments" text={String(report.paymentCount)}/></div>{report.varianceReason&&<p className="mt-4 rounded-xl bg-amber-50 p-4 text-sm"><b>Variance reason:</b> {report.varianceReason}</p>}<div className="mt-6 flex flex-wrap gap-3"><button onClick={()=>window.print()} className="min-h-11 rounded-xl bg-[#18241f] px-5 font-black text-white">Print</button><button onClick={download} className="min-h-11 rounded-xl border border-line px-5 font-black">Download</button><button onClick={onDone} className="min-h-11 rounded-xl border border-line px-5 font-black">Done</button></div></section>;}
function State({title,detail,retry}:{title:string;detail:string;retry?:()=>void}){return <section className="grid min-h-72 place-items-center text-center"><div><h1 className="text-2xl font-black">{title}</h1><p className="mt-2 text-sm text-ink-muted">{detail}</p>{retry&&<button onClick={retry} className="mt-4 min-h-11 rounded-xl bg-[#18241f] px-5 font-black text-white">Try again</button>}</div></section>;}
