'use client';

import { useEffect, useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ApiError, apiRequest, type ApiEnvelope } from '@/lib/api-client';
import { useAuth } from './auth-provider';
import { useBranch } from './shell/branch-provider';
import { useLocale } from '@/components/locale-provider';

interface ShiftProjection { id:string; status:'OPEN'; openingCashMinor:string; approvedCashMinor:string; expectedCashMinor:string; cashOrderCount:number; cashPaymentCount:number; openedAt:string; version:number; }
interface ShiftReport { id:string; cashShiftId:string; openingCashMinor:string; approvedCashMinor:string; expectedCashMinor:string; countedCashMinor:string; varianceMinor:string; varianceReason:string|null; orderCount:number; paymentCount:number; localOpenedAt:string; localClosedAt:string; localBusinessDate:string; }

function etbToMinor(value:string):string|null { const normalized=value.trim().replace(/,/g,''); if(!/^\d{1,14}(?:\.\d{1,2})?$/.test(normalized))return null; const [whole,fraction='']=normalized.split('.'); return (BigInt(whole)*100n+BigInt(fraction.padEnd(2,'0'))).toString(); }

export function CashShiftWorkspace(){
  const { formatCurrency, tr } = useLocale();
  const {accessToken,csrfToken,profile}=useAuth(); const membership=profile?.memberships[0];
  const {branchId}=useBranch();
  const tenantId=membership?.tenant.id??''; const [online,setOnline]=useState(true); const [opening,setOpening]=useState(''); const [counted,setCounted]=useState(''); const [reason,setReason]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string|null>(null); const [report,setReport]=useState<ShiftReport|null>(null); const [clock,setClock]=useState(0);
  useEffect(()=>{const update=()=>setOnline(navigator.onLine);update();window.addEventListener('online',update);window.addEventListener('offline',update);const timer=window.setInterval(()=>setClock((value)=>value+1),60_000);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update);window.clearInterval(timer);};},[]);
  const query=useQuery({queryKey:['current-shift',tenantId,branchId],enabled:Boolean(accessToken&&tenantId&&branchId),queryFn:async()=> (await apiRequest<ApiEnvelope<ShiftProjection|null>>(`/branches/${branchId}/shifts/current`,{accessToken,tenantId})).data,refetchInterval:15_000});
  const shift=query.data; const countedMinor=etbToMinor(counted); const variance=shift&&countedMinor!==null?BigInt(countedMinor)-BigInt(shift.expectedCashMinor):null; const elapsed=useMemo(()=>shift?Math.max(0,Math.floor((Date.now()-new Date(shift.openedAt).getTime())/60_000)):0,[shift,clock]);
  async function openShift(event:React.FormEvent){event.preventDefault();const minor=etbToMinor(opening);if(minor===null)return setMessage(tr('shifts.invalidOpening'));if(!online)return setMessage(tr('shifts.offlineOpen'));setBusy(true);setMessage(null);try{await apiRequest(`/branches/${branchId}/shifts/open`,{method:'POST',body:{openingCashMinor:minor},accessToken,csrfToken,tenantId});setOpening('');await query.refetch();}catch(error){setMessage(error instanceof ApiError?error.message:tr('shifts.openError'));}finally{setBusy(false);}}
  async function closeShift(event:React.FormEvent){event.preventDefault();if(!shift||countedMinor===null)return setMessage(tr('shifts.enterCounted'));if(variance!==0n&&!reason.trim())return setMessage(tr('shifts.needReason'));if(!online)return setMessage(tr('shifts.offlineClose'));setBusy(true);setMessage(null);try{const result=await apiRequest<{shift:ShiftProjection;report:ShiftReport}>(`/branches/${branchId}/shifts/${shift.id}/close`,{method:'POST',body:{countedCashMinor:countedMinor,varianceReason:variance===0n?undefined:reason.trim(),expectedVersion:shift.version},accessToken,csrfToken,tenantId});setReport(result.report);setCounted('');setReason('');await query.refetch();}catch(error){if(error instanceof ApiError&&error.status===409){await query.refetch();setMessage(tr('shifts.conflictMsg'));}else setMessage(error instanceof ApiError?error.message:tr('shifts.closeShiftError'));}finally{setBusy(false);}}
if(!membership||!['OWNER','MANAGER','CASHIER'].includes(membership.role))return <State title={tr('shifts.permissionTitle')} detail={tr('shifts.permissionDeniedDetail')}/>;
if(query.isLoading)return <State title={tr('shifts.loadingShiftTitle')} detail={tr('shifts.loadingShiftDetail')}/>;
if(query.isError)return <State title={tr('shifts.unavailableTitle')} detail={tr('shifts.reconnectDetail')} retry={()=>void query.refetch()}/>;
  if(report)return <Report report={report} onDone={()=>setReport(null)}/>;
  return <><header className="mb-7"><p className="text-xs font-black uppercase tracking-wider text-brand">{tr('shifts.cashEyebrow')}</p><h1 className="mt-2 text-3xl font-black">{tr(shift?'shifts.currentShift':'shifts.openYourShift')}</h1><p className="mt-2 text-sm text-ink-muted">{shift?tr('shifts.currentSub',{h:Math.floor(elapsed/60),m:elapsed%60}):tr('shifts.openSub')}</p></header>{!online&&<div role="status" className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 font-bold text-red-800">{tr('shifts.offlineShift')}</div>}{message&&<div role="alert" className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-900">{message}</div>}
  {!shift?<form onSubmit={openShift} className="max-w-xl rounded-2xl border border-line bg-white p-6 shadow-card"><label className="block text-sm font-black">{tr('shifts.openingCashLabel')}<input autoFocus inputMode="decimal" value={opening} onChange={(event)=>setOpening(event.target.value)} placeholder="0.00" className="mt-2 min-h-12 w-full rounded-xl border border-line px-4 text-lg tabular-nums"/></label><button disabled={busy||!online} className="mt-5 min-h-12 w-full rounded-xl bg-dark font-black text-white disabled:opacity-50">{busy?tr('shifts.opening'):tr('shifts.openCashShift')}</button></form>:
  <div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label={tr('shifts.openingCash')} value={shift.openingCashMinor}/><Metric label={tr('shifts.confirmedCash')} value={shift.approvedCashMinor} detail={tr('shifts.cashOrders',{count:shift.cashOrderCount})}/><Metric label={tr('shifts.expectedDrawer')} value={shift.expectedCashMinor}/><Metric label={tr('shifts.elapsedLabel')} text={tr('shifts.elapsedText',{h:Math.floor(elapsed/60),m:elapsed%60})} detail={tr('shifts.approvedPayments',{count:shift.cashPaymentCount})}/></div><form onSubmit={closeShift} className="mt-5 max-w-3xl rounded-2xl border border-line bg-white p-6 shadow-card"><h2 className="text-xl font-black">{tr('shifts.closeReconciliation')}</h2><p className="mt-1 text-sm text-ink-muted">{tr('shifts.closeCountHint')}</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-black">{tr('shifts.countedCashLabel')}<input inputMode="decimal" value={counted} onChange={(event)=>setCounted(event.target.value)} placeholder={tr('shifts.countedPlaceholder')} className="mt-2 min-h-12 w-full rounded-xl border border-line px-4 tabular-nums"/></label><div className="rounded-xl bg-muted p-4"><p className="text-xs font-bold text-ink-muted">{tr('shifts.varianceLabel')}</p><p className={`mt-2 text-xl font-black tabular-nums ${variance&&variance!==0n?'text-red-700':''}`}>{variance===null?'—':formatCurrency(variance)}</p></div></div>{variance!==null&&variance!==0n&&<label className="mt-4 block text-sm font-black">{tr('shifts.varianceReasonLabel')}<textarea required maxLength={255} value={reason} onChange={(event)=>setReason(event.target.value)} className="mt-2 min-h-24 w-full rounded-xl border border-line p-3"/></label>}<button disabled={busy||!online||countedMinor===null} className="mt-5 min-h-12 rounded-xl bg-red-700 px-6 font-black text-white disabled:opacity-50">{busy?tr('shifts.closing'):tr('shifts.closeAndReport')}</button></form></div>}</>;
}
function Metric({label,value,text,detail}:{label:string;value?:string;text?:string;detail?:string}){const { formatCurrency } = useLocale(); return <section className="rounded-2xl border border-line bg-white p-5 shadow-card"><p className="text-sm font-bold text-ink-muted">{label}</p><p className="mt-3 text-2xl font-black tabular-nums">{text??formatCurrency(value??'0')}</p>{detail&&<p className="mt-2 text-xs text-ink-muted">{detail}</p>}</section>;}
function Report({report,onDone}:{report:ShiftReport;onDone:()=>void}){const { tr } = useLocale();function download(){const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`shift-${report.cashShiftId}.json`;link.click();URL.revokeObjectURL(url);}return <section className="rounded-2xl border border-line bg-white p-6 shadow-card"><p className="text-xs font-black uppercase tracking-wider text-emerald-700">{tr('shifts.shiftClosed')}</p><h1 className="mt-2 text-3xl font-black">{tr('shifts.reportTitle')}</h1><div className="mt-6 grid gap-3 sm:grid-cols-2"><Metric label={tr('shifts.openingCash')} value={report.openingCashMinor}/><Metric label={tr('shifts.confirmedCash')} value={report.approvedCashMinor}/><Metric label={tr('shifts.expectedDrawer')} value={report.expectedCashMinor}/><Metric label={tr('shifts.countedCash')} value={report.countedCashMinor}/><Metric label={tr('shifts.variance')} value={report.varianceMinor}/><Metric label={tr('shifts.cashPayments')} text={String(report.paymentCount)}/></div>{report.varianceReason&&<p className="mt-4 rounded-xl bg-amber-50 p-4 text-sm"><b>{tr('shifts.varianceReasonPrefix')}</b> {report.varianceReason}</p>}<div className="mt-6 flex flex-wrap gap-3"><button onClick={()=>window.print()} className="min-h-11 rounded-xl bg-dark px-5 font-black text-white">{tr('shifts.print')}</button><button onClick={download} className="min-h-11 rounded-xl border border-line px-5 font-black">{tr('shifts.download')}</button><button onClick={onDone} className="min-h-11 rounded-xl border border-line px-5 font-black">{tr('shifts.done')}</button></div></section>;}
function State({title,detail,retry}:{title:string;detail:string;retry?:()=>void}){const { tr } = useLocale();return <section className="grid min-h-72 place-items-center text-center"><div><h1 className="text-2xl font-black">{title}</h1><p className="mt-2 text-sm text-ink-muted">{detail}</p>{retry&&<button onClick={retry} className="mt-4 min-h-11 rounded-xl bg-dark px-5 font-black text-white">{tr('common.tryAgain')}</button>}</div></section>;}
