'use client';
import Link from 'next/link';
import { useState } from 'react';

function CustomerShell({children,step}:{children:React.ReactNode;step:number}) { return <main className="min-h-screen bg-[#fffaf3]"><header className="border-b border-line bg-[#14201b] px-5 py-4 text-white"><div className="mx-auto flex max-w-5xl items-center justify-between"><Link href="/order/bole-main" className="font-black">Buna House</Link><span className="text-xs font-bold text-white/60">Bole Main · Table 08</span></div></header><div className="mx-auto max-w-5xl px-4 py-7"><div className="mb-7 flex items-center gap-2">{['Menu','Checkout','Payment','Tracking'].map((x,i)=><div className="flex flex-1 items-center gap-2" key={x}><span className={`grid size-7 shrink-0 place-items-center rounded-full text-xs font-black ${i<=step?'bg-brand text-white':'bg-muted text-ink-muted'}`}>{i+1}</span><span className="hidden text-xs font-black sm:block">{x}</span>{i<3&&<span className="h-px flex-1 bg-line"/>}</div>)}</div>{children}</div></main> }

export function CheckoutWorkflow() {
  const [method,setMethod]=useState('TRANSFER');
  return <CustomerShell step={1}><div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><section className="rounded-2xl border border-line bg-white p-5 shadow-card"><p className="text-xs font-black uppercase tracking-widest text-brand">Checkout</p><h1 className="mt-2 text-3xl font-black">How would you like to pay?</h1><p className="mt-2 text-sm text-ink-muted">Your order is held until payment is confirmed.</p><div className="mt-6 space-y-3">{[['TRANSFER','Manual mobile transfer','Pay using Telebirr, CBE Birr, or M-PESA and upload proof.'],['CASH','Pay cashier','Place the order and settle directly with the cashier.'],['GATEWAY','Online payment','Unavailable for this restaurant.']].map(x=><button disabled={x[0]==='GATEWAY'} onClick={()=>setMethod(x[0])} className={`w-full rounded-xl border p-4 text-left disabled:opacity-40 ${method===x[0]?'border-brand bg-orange-50':'border-line'}`} key={x[0]}><b>{x[1]}</b><p className="mt-1 text-xs text-ink-muted">{x[2]}</p></button>)}</div>{method==='TRANSFER'&&<div className="mt-5 rounded-xl bg-[#16231e] p-5 text-white"><p className="text-xs font-bold text-white/50">SEND EXACTLY</p><p className="mt-1 text-2xl font-black">ETB 840</p><p className="mt-4 text-sm">Telebirr: <b>0911 234 567</b></p><p className="mt-1 text-sm">Account: Buna House PLC</p></div>}<Link href={method==='TRANSFER'?'/order/bole-main/payment':'/order/bole-main/track'} className="mt-5 block rounded-xl bg-brand py-4 text-center font-black text-white">Continue →</Link></section><OrderSummary/></div></CustomerShell>;
}

export function PaymentProofWorkflow() {
  const [uploaded,setUploaded]=useState(false);
  return <CustomerShell step={2}><div className="mx-auto max-w-2xl rounded-2xl border border-line bg-white p-5 shadow-card sm:p-7"><p className="text-xs font-black uppercase tracking-widest text-brand">Manual transfer</p><h1 className="mt-2 text-3xl font-black">Upload payment proof</h1><p className="mt-2 text-sm text-ink-muted">A cashier will verify the screenshot before sending your order to the kitchen.</p><label className="mt-6 grid min-h-64 cursor-pointer place-items-center rounded-2xl border-2 border-dashed border-line bg-muted/50 p-8 text-center"><input type="file" accept="image/*" className="sr-only" onChange={()=>setUploaded(true)}/><div><span className="mx-auto grid size-14 place-items-center rounded-xl bg-white text-2xl shadow-sm">↑</span><p className="mt-4 font-black">{uploaded?'payment-proof.jpg selected':'Choose screenshot'}</p><p className="mt-1 text-xs text-ink-muted">JPG, PNG or WEBP · up to 8 MB</p></div></label><label className="mt-5 block text-xs font-black text-ink-muted">Transaction reference<input className="mt-2 w-full rounded-xl border border-line p-3 text-sm" placeholder="Example: FT26082391"/></label><Link href="/order/bole-main/track" className={`mt-5 block rounded-xl py-4 text-center font-black text-white ${uploaded?'bg-brand':'pointer-events-none bg-stone-300'}`}>Submit for verification</Link></div></CustomerShell>;
}

export function TrackingWorkflow() {
  const [stage,setStage]=useState(1); const steps=[['Payment review','Cashier is checking your transfer'],['Confirmed','Your order was sent to the kitchen'],['Preparing','The kitchen is preparing your meal'],['Ready','Your order is ready']];
  return <CustomerShell step={3}><div className="mx-auto max-w-2xl rounded-2xl border border-line bg-white p-5 shadow-card sm:p-7"><div className="flex justify-between gap-4"><div><p className="text-xs font-black text-brand">ORDER #1049</p><h1 className="mt-2 text-3xl font-black">We have your order</h1></div><span className="h-fit rounded-full bg-amber-50 px-3 py-2 text-xs font-black text-amber-800">20–30 MIN</span></div><div className="mt-8 space-y-0">{steps.map((x,i)=><div className="flex gap-4" key={x[0]}><div className="flex flex-col items-center"><span className={`grid size-8 place-items-center rounded-full text-xs font-black ${i<=stage?'bg-brand text-white':'bg-muted text-ink-muted'}`}>{i<stage?'✓':i+1}</span>{i<3&&<span className={`h-16 w-0.5 ${i<stage?'bg-brand':'bg-line'}`}/>}</div><div><h2 className={`font-black ${i>stage?'text-ink-muted':''}`}>{x[0]}</h2><p className="mt-1 text-sm text-ink-muted">{x[1]}</p></div></div>)}</div><button onClick={()=>setStage(Math.min(3,stage+1))} className="mt-5 w-full rounded-xl border border-line py-3 text-xs font-black">Simulate next update</button><div className="mt-5 rounded-xl bg-muted p-4 text-sm"><div className="flex justify-between"><span>Table 08 · 3 items</span><b>ETB 840</b></div></div></div></CustomerShell>;
}

function OrderSummary(){return <section className="h-fit rounded-2xl border border-line bg-white p-5 shadow-card"><h2 className="text-lg font-black">Your order</h2>{[['Special Tibs','1','ETB 400'],['Shiro Wot','1','ETB 290'],['Fresh Spris','1','ETB 130']].map(x=><div className="mt-4 flex justify-between border-b border-line pb-4 text-sm" key={x[0]}><span><b>{x[1]} × {x[0]}</b></span><b>{x[2]}</b></div>)}<div className="mt-4 flex justify-between text-xl font-black"><span>Total</span><span>ETB 840</span></div></section>}
