'use client';

import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { BrandMark } from './brand-mark';
import { formatEtb, mockMenuApi } from '@/lib/mock-api';
import type { CartLine, MenuItem } from '@/lib/types';

export function CustomerMenu() {
  const { data, isLoading } = useQuery({ queryKey: ['public-menu', 'bole-main'], queryFn: () => mockMenuApi.getMenu() });
  const [category, setCategory] = useState('all');
  const [cart, setCart] = useState<CartLine[]>([]);
  const [cartOpen, setCartOpen] = useState(false);

  const items = useMemo(() => data?.items.filter((item) => category === 'all' || (category === 'popular' ? Boolean(item.badge) : item.categoryId === category)) ?? [], [category, data]);
  const count = cart.reduce((sum, line) => sum + line.quantity, 0);
  const subtotal = cart.reduce((sum, line) => sum + line.item.priceMinor * line.quantity, 0);

  const add = (item: MenuItem) => setCart((current) => {
    const existing = current.find((line) => line.item.id === item.id);
    return existing ? current.map((line) => line.item.id === item.id ? { ...line, quantity: line.quantity + 1 } : line) : [...current, { item, quantity: 1 }];
  });
  const change = (id: string, delta: number) => setCart((current) => current.map((line) => line.item.id === id ? { ...line, quantity: line.quantity + delta } : line).filter((line) => line.quantity > 0));

  return (
    <main className="min-h-screen bg-[#fffaf3] pb-24 lg:pb-10">
      <header className="sticky top-0 z-30 border-b border-black/[0.06] bg-[#fffaf3]/92 backdrop-blur-xl"><div className="mx-auto flex min-h-[72px] max-w-7xl items-center justify-between px-4 sm:px-7"><div className="text-[#121816]"><BrandMark onDark={false} /></div><div className="flex items-center gap-2"><span className="hidden rounded-full bg-emerald-50 px-3 py-2 text-xs font-black text-emerald-700 sm:inline">Open · closes 10 PM</span><button onClick={() => setCartOpen(true)} className="relative grid size-11 place-items-center rounded-xl bg-[#18241f] text-lg text-white" aria-label={`Open cart with ${count} items`}>▢{count > 0 && <span className="absolute -right-1.5 -top-1.5 grid size-5 place-items-center rounded-full bg-brand text-[10px] font-black">{count}</span>}</button></div></div></header>

      <section className="relative overflow-hidden bg-[#18241f] text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(192,138,46,.22),transparent_32rem)]" /><div className="relative mx-auto grid min-h-[340px] max-w-7xl items-center gap-8 px-4 py-12 sm:px-7 lg:grid-cols-[1.15fr_.85fr]"><div><span className="inline-flex rounded-full border border-white/15 bg-white/[0.07] px-3 py-2 text-[10px] font-black uppercase tracking-[0.18em] text-amber-300">Bole Main · Table 08</span><h1 className="mt-6 max-w-2xl text-4xl font-black leading-[1.05] tracking-[-0.055em] sm:text-5xl">Made with warmth.<br />Served with pride.</h1><p className="mt-5 max-w-xl text-sm leading-7 text-white/55 sm:text-base">Ethiopian favourites, fresh ingredients, and the unmistakable welcome of Buna House.</p><div className="mt-7 flex flex-wrap gap-5 text-xs text-white/55"><span>◷ 20–30 min</span><span>★ 4.8 guest rating</span><span>⌖ Bole Atlas</span></div></div><div className="hidden h-64 rotate-2 rounded-[2rem] border border-white/10 bg-[linear-gradient(145deg,#b4532a,#4a2c21)] p-7 shadow-2xl lg:flex lg:flex-col lg:justify-between"><span className="text-5xl font-black text-white/20">BH</span><div><p className="text-xs font-black uppercase tracking-widest text-amber-200">Today’s recommendation</p><p className="mt-2 text-2xl font-black">Special Tibs</p><p className="mt-1 text-sm text-white/55">Rosemary, peppers and freshly baked injera</p></div></div></div></section>

      <div className="mx-auto max-w-7xl px-4 sm:px-7"><div className="hide-scrollbar sticky top-[72px] z-20 -mx-4 flex gap-2 overflow-x-auto border-b border-line bg-[#fffaf3]/95 px-4 py-4 backdrop-blur-xl sm:-mx-7 sm:px-7">{data?.categories.map((item) => <button key={item.id} onClick={() => setCategory(item.id)} className={`min-h-10 shrink-0 rounded-full px-4 text-xs font-black ${category === item.id ? 'bg-brand text-white' : 'border border-line bg-white text-ink-muted'}`}>{item.name}</button>)}</div>
        <div className="grid gap-8 py-8 lg:grid-cols-[1fr_340px]"><section><div className="mb-5 flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-brand">Explore the menu</p><h2 className="mt-2 text-2xl font-black tracking-[-0.035em]">{data?.categories.find((item) => item.id === category)?.name ?? 'All items'}</h2></div><p className="text-xs font-bold text-ink-muted">{items.length} dishes</p></div>
          {isLoading ? <div className="grid gap-4 sm:grid-cols-2">{Array.from({ length: 6 }).map((_, index) => <div key={index} className="h-40 animate-pulse rounded-card bg-white" />)}</div> : <div className="grid gap-4 sm:grid-cols-2">{items.map((item) => <article key={item.id} className={`group flex min-h-40 overflow-hidden rounded-card border border-line bg-white shadow-card ${!item.available ? 'opacity-55' : ''}`}><div className="relative grid w-[36%] min-w-28 place-items-center text-xl font-black text-white" style={{ background: `linear-gradient(145deg, ${item.tone}, #18201d)` }}>{item.initials}{item.badge && <span className="absolute left-2 top-2 rounded-full bg-white/90 px-2 py-1 text-[8px] font-black text-ink">{item.badge}</span>}</div><div className="flex min-w-0 flex-1 flex-col p-4"><h3 className="font-black">{item.name}</h3><p className="mt-1 line-clamp-2 text-xs leading-5 text-ink-muted">{item.description}</p><div className="mt-auto flex items-center justify-between pt-3"><span className="text-sm font-black text-brand">{formatEtb(item.priceMinor)}</span><button disabled={!item.available} onClick={() => add(item)} className="grid size-10 place-items-center rounded-xl bg-muted text-xl font-bold text-brand transition group-hover:bg-brand group-hover:text-white disabled:text-ink-muted" aria-label={`Add ${item.name}`}>{item.available ? '+' : '×'}</button></div></div></article>)}</div>}
        </section><aside className="hidden lg:block"><CustomerCart cart={cart} subtotal={subtotal} change={change} /></aside></div>
      </div>

      {count > 0 && <button onClick={() => setCartOpen(true)} className="fixed inset-x-4 bottom-4 z-30 flex min-h-14 items-center justify-between rounded-2xl bg-brand px-5 text-white shadow-float lg:hidden"><span className="text-sm font-black">View order · {count} {count === 1 ? 'item' : 'items'}</span><span className="text-sm font-black">{formatEtb(subtotal)}</span></button>}
      {cartOpen && <div className="fixed inset-0 z-50 flex items-end bg-black/50 lg:hidden" onClick={(event) => { if (event.currentTarget === event.target) setCartOpen(false); }}><div className="max-h-[88vh] w-full overflow-y-auto rounded-t-[1.5rem] bg-[#fffaf3] p-4 shadow-float"><div className="mx-auto mb-3 h-1.5 w-12 rounded-full bg-black/15" /><div className="mb-3 flex items-center justify-between"><h2 className="text-xl font-black">Your order</h2><button onClick={() => setCartOpen(false)} className="grid size-10 place-items-center rounded-xl border border-line" aria-label="Close cart">×</button></div><CustomerCart cart={cart} subtotal={subtotal} change={change} mobile /></div></div>}
    </main>
  );
}

function CustomerCart({ cart, subtotal, change, mobile = false }: { cart: CartLine[]; subtotal: number; change: (id: string, delta: number) => void; mobile?: boolean }) {
  return <div className={`${mobile ? '' : 'sticky top-[145px]'} overflow-hidden rounded-panel border border-line bg-white shadow-card`}><div className="border-b border-line p-5"><p className="text-[10px] font-black uppercase tracking-[0.16em] text-brand">Table 08</p><h2 className="mt-1 text-xl font-black">Your order</h2></div><div className="p-5">{cart.length === 0 ? <div className="py-12 text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-muted text-2xl">▢</span><p className="mt-4 text-sm font-black">Nothing here yet</p><p className="mt-2 text-xs text-ink-muted">Add something delicious from the menu.</p></div> : <div className="space-y-4">{cart.map((line) => <div key={line.item.id}><div className="flex justify-between gap-3"><div><p className="text-sm font-black">{line.item.name}</p><p className="mt-1 text-xs text-ink-muted">{formatEtb(line.item.priceMinor)} each</p></div><p className="text-sm font-black">{formatEtb(line.item.priceMinor * line.quantity)}</p></div><div className="mt-2 flex items-center justify-between"><button className="text-[10px] font-bold text-brand">Add instructions</button><div className="flex items-center rounded-lg border border-line"><button onClick={() => change(line.item.id, -1)} className="grid size-8 place-items-center" aria-label={`Remove one ${line.item.name}`}>−</button><span className="min-w-7 text-center text-xs font-black">{line.quantity}</span><button onClick={() => change(line.item.id, 1)} className="grid size-8 place-items-center" aria-label={`Add one ${line.item.name}`}>+</button></div></div></div>)}</div>}</div>{cart.length > 0 && <div className="border-t border-line bg-[#fcfaf6] p-5"><div className="flex items-center justify-between"><span className="text-sm text-ink-muted">Subtotal</span><span className="font-black">{formatEtb(subtotal)}</span></div><p className="mt-2 text-[10px] leading-4 text-ink-muted">Taxes and service charges, if applicable, are calculated at checkout.</p><button className="mt-4 min-h-12 w-full rounded-control bg-brand text-sm font-black text-white">Review order</button></div>}</div>;
}
