'use client';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { BrandMark } from './brand-mark';
import { formatEtb, mockMenuApi } from '@/lib/mock-api';
import type { CartLine, MenuItem } from '@/lib/types';

export function CustomerMenu() {
  const {data,isLoading}=useQuery({queryKey:['public-menu','bole-main'],queryFn:()=>mockMenuApi.getMenu()});
  const [category,setCategory]=useState('all'); const [cart,setCart]=useState<CartLine[]>([]); const [cartOpen,setCartOpen]=useState(false);
  const items=useMemo(()=>data?.items.filter(x=>category==='all'||category==='popular'&&x.badge||x.categoryId===category)??[],[data,category]);
  const count=cart.reduce((sum,x)=>sum+x.quantity,0); const subtotal=cart.reduce((sum,x)=>sum+x.item.priceMinor*x.quantity,0);
  function add(item:MenuItem){setCart(v=>{const line=v.find(x=>x.item.id===item.id);return line?v.map(x=>x.item.id===item.id?{...x,quantity:x.quantity+1}:x):[...v,{item,quantity:1}]})}
  function change(id:string,delta:number){setCart(v=>v.map(x=>x.item.id===id?{...x,quantity:x.quantity+delta}:x).filter(x=>x.quantity>0))}
  return <main className="min-h-screen bg-[#fffaf3] pb-24 lg:pb-8"><header className="sticky top-0 z-30 border-b border-line bg-[#fffaf3]/90 backdrop-blur-xl"><div className="mx-auto flex min-h-[72px] max-w-7xl items-center justify-between px-4 sm:px-7"><BrandMark onDark={false}/><button onClick={()=>setCartOpen(true)} aria-label={`Open cart with ${count} items`} className="relative grid size-11 place-items-center rounded-xl bg-[#18241f] text-white">▢{count>0&&<span className="absolute -right-1 -top-1 grid size-5 place-items-center rounded-full bg-brand text-[9px] font-black">{count}</span>}</button></div></header>
  <section className="bg-[#14201b] px-4 py-10 text-white"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[.18em] text-[#e3b262]">Bole Main · Table 08</p><h1 className="mt-3 max-w-2xl text-4xl font-black tracking-[-.05em] sm:text-5xl">Made with warmth.<br/>Served with pride.</h1><p className="mt-4 text-sm text-white/60">Ethiopian favourites · 20–30 min · Open until 10 PM</p></div></section>
  <div className="mx-auto max-w-7xl px-4 sm:px-7"><div className="hide-scrollbar sticky top-[72px] z-20 -mx-4 flex gap-2 overflow-auto border-b border-line bg-[#fffaf3]/95 px-4 py-4 sm:-mx-7 sm:px-7">{data?.categories.map(x=><button key={x.id} onClick={()=>setCategory(x.id)} className={`shrink-0 rounded-full px-4 py-2 text-xs font-black ${category===x.id?'bg-brand text-white':'border border-line bg-white text-ink-muted'}`}>{x.name}</button>)}</div><div className="grid gap-6 py-7 lg:grid-cols-[1fr_360px]"><section><p className="text-xs font-black uppercase tracking-[.16em] text-brand">Explore the menu</p><h2 className="mt-2 text-2xl font-black">{data?.categories.find(x=>x.id===category)?.name}</h2>{isLoading?<div className="mt-5 grid gap-4 sm:grid-cols-2">{Array.from({length:6},(_,i)=><div className="h-40 animate-pulse rounded-xl bg-white" key={i}/>)}</div>:<div className="mt-5 grid gap-4 sm:grid-cols-2">{items.map(item=><article className={`flex min-h-40 overflow-hidden rounded-2xl border border-line bg-white shadow-card ${item.available?'':'opacity-50'}`} key={item.id}><div className="relative grid w-2/5 place-items-center text-xl font-black text-white" style={{background:`linear-gradient(145deg,${item.tone},#18201d)`}}>{item.initials}{item.badge&&<span className="absolute left-2 top-2 rounded-full bg-white/90 px-2 py-1 text-[8px] text-ink">{item.badge}</span>}</div><div className="flex flex-1 flex-col p-4"><h3 className="font-black">{item.name}</h3><p className="mt-1 text-xs leading-5 text-ink-muted">{item.description}</p><div className="mt-auto flex items-center justify-between"><b className="text-brand">{formatEtb(item.priceMinor)}</b><button disabled={!item.available} onClick={()=>add(item)} aria-label={`Add ${item.name}`} className="grid size-10 place-items-center rounded-xl bg-muted text-xl font-black text-brand">{item.available?'+':'×'}</button></div></div></article>)}</div>}</section><div className="hidden lg:block"><Cart cart={cart} subtotal={subtotal} change={change}/></div></div></div>
  {count>0&&<button onClick={()=>setCartOpen(true)} className="fixed inset-x-4 bottom-4 z-30 flex min-h-14 items-center justify-between rounded-2xl bg-brand px-5 font-black text-white shadow-float lg:hidden"><span>View order · {count} items</span><span>{formatEtb(subtotal)}</span></button>}
  {cartOpen&&<div className="fixed inset-0 z-50 flex items-end bg-black/45 lg:hidden" onClick={e=>{if(e.currentTarget===e.target)setCartOpen(false)}}><div className="max-h-[88vh] w-full overflow-auto rounded-t-3xl bg-[#fffaf3] p-4"><div className="mb-3 flex justify-between"><h2 className="text-xl font-black">Your order</h2><button onClick={()=>setCartOpen(false)} aria-label="Close cart">×</button></div><Cart cart={cart} subtotal={subtotal} change={change}/></div></div>}</main>;
}
function Cart({cart,subtotal,change}:{cart:CartLine[];subtotal:number;change:(id:string,d:number)=>void}){return <div className="overflow-hidden rounded-2xl border border-line bg-white shadow-card"><div className="border-b border-line p-5"><p className="text-[10px] font-black text-brand">TABLE 08</p><h2 className="mt-1 text-xl font-black">Your order</h2></div><div className="p-5">{cart.length===0?<p className="py-10 text-center text-sm font-bold text-ink-muted">Add something delicious.</p>:<div className="space-y-4">{cart.map(x=><div key={x.item.id}><div className="flex justify-between text-sm"><b>{x.item.name}</b><b>{formatEtb(x.item.priceMinor*x.quantity)}</b></div><div className="mt-2 flex justify-end"><div className="flex items-center rounded-lg border border-line"><button onClick={()=>change(x.item.id,-1)} className="grid size-8 place-items-center">−</button><span className="w-7 text-center text-xs font-black">{x.quantity}</span><button onClick={()=>change(x.item.id,1)} className="grid size-8 place-items-center">+</button></div></div></div>)}</div>}</div>{cart.length>0&&<div className="border-t border-line bg-muted/50 p-5"><div className="flex justify-between"><span>Subtotal</span><b>{formatEtb(subtotal)}</b></div><Link href="/order/bole-main/checkout" className="mt-4 grid min-h-12 place-items-center rounded-xl bg-brand text-sm font-black text-white">Review order</Link></div>}</div>}
