'use client';
import { useState } from 'react';

const data = {
  orders: { eyebrow:'Operations', title:'Orders', copy:'Track every active and completed order across this branch.', action:'+ New order', cards:[['#1048 · Table 08','IN PROGRESS','2 × Special Tibs · ETB 1,840'],['#1047 · Meron T.','PAYMENT REVIEW','Pickup · ETB 920'],['#1046 · Counter','READY','4 items · ETB 1,365'],['#1045 · Table 03','CONFIRMED','2 items · ETB 675']] },
  kitchen: { eyebrow:'Kitchen display', title:'Live kitchen queue', copy:'Orders appear as soon as payment is confirmed.', cards:[['#1045 · Table 03','CONFIRMED','2 × Shiro Wot'],['#1048 · Table 08','IN PROGRESS','2 × Special Tibs · 1 × Spris'],['#1046 · Counter','READY','4 items ready to serve']] },
  menu: { eyebrow:'Catalog', title:'Menu management', copy:'Manage dishes, prices, categories, and availability.', action:'+ Add menu item', cards:[['Special Tibs','ETB 400','Main dishes'],['Shiro Wot','ETB 290','Main dishes'],['Beyaynetu','ETB 350','Main dishes'],['Special Firfir','ETB 260','Breakfast'],['Buna Ceremony','ETB 150','Drinks'],['House Baklava','ETB 120','Unavailable']] },
  inventory: { eyebrow:'Stock control', title:'Inventory & batches', copy:'Monitor portions, consumption, and low-stock risk.', action:'+ Receive batch', cards:[['Beef portions','18 / 70','LOW STOCK'],['Injera','84 / 120','HEALTHY'],['Coffee servings','42 / 60','HEALTHY'],['Chicken portions','31 / 50','HEALTHY']] },
  reports: { eyebrow:'Analytics', title:'Reports', copy:'Branch performance for Aug 13–19, 2026.', action:'Export report', cards:[['Net revenue','ETB 326,840','+12.4%'],['Orders','428','+8.1%'],['Average order','ETB 764','+3.7%'],['Avg. prep time','18 min','-2 min']] },
  settings: { eyebrow:'Administration', title:'Team & settings', copy:'Control restaurant identity, access, branches, and modules.', cards:[['Restaurant appearance','Buna House','Brand colours and storefront'],['Team members','12 active','Owners, managers and staff'],['Branches','2 locations','Bole Main and Downtown'],['Feature modules','3 enabled','QR, KDS and inventory']] },
} as const;

export function OperationsPage({kind}:{kind:keyof typeof data}) {
  const page=data[kind]; const [done,setDone]=useState<string[]>([]);
  return <><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-brand">{page.eyebrow}</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">{page.title}</h1><p className="mt-2 text-sm text-ink-muted">{page.copy}</p></div>{'action' in page&&<button className="rounded-xl bg-[#18201d] px-5 py-3 text-sm font-bold text-white">{page.action}</button>}</div>
  {kind==='orders'&&<div className="mb-5 flex gap-2 overflow-auto">{['All','Payment review','Confirmed','In progress','Ready'].map((x,i)=><button className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-bold ${i?'bg-white text-ink-muted':'bg-[#18201d] text-white'}`} key={x}>{x}</button>)}</div>}
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{page.cards.filter(x=>!done.includes(x[0])).map((x,i)=><article className="rounded-2xl border border-black/[.07] bg-white p-5 shadow-sm" key={x[0]}><div className="mb-5 grid h-24 place-items-center rounded-xl bg-gradient-to-br from-[#b4532a] to-[#17231f] text-2xl font-black text-white">{kind==='reports'?<span className="text-4xl">↗</span>:x[0].split(' ').slice(0,2).map(y=>y[0]).join('')}</div><h2 className="text-lg font-black">{x[0]}</h2><p className="mt-2 text-sm font-bold text-brand">{x[1]}</p><p className="mt-1 text-sm text-ink-muted">{x[2]}</p>{kind==='kitchen'&&<button onClick={()=>setDone(v=>[...v,x[0]])} className="mt-5 w-full rounded-xl bg-[#18201d] py-3 text-sm font-black text-white">Move forward →</button>}{kind==='menu'&&<label className="mt-5 flex items-center justify-between border-t border-line pt-4 text-xs font-bold text-ink-muted">Available<input type="checkbox" defaultChecked={i<5} className="size-5 accent-[#b4532a]"/></label>}{kind==='settings'&&<button className="mt-5 text-sm font-black text-brand">Manage →</button>}</article>)}</div></>;
}
