'use client';

import Link from 'next/link';
import { useState } from 'react';

export function PageTitle({ label, title, copy, action }: { label: string; title: string; copy: string; action?: React.ReactNode }) {
  return <header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-brand">{label}</p><h1 className="mt-2 text-3xl font-black tracking-[-.04em] sm:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-ink-muted">{copy}</p></div>{action}</header>;
}
export function Panel({ children, className='' }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-panel border border-line bg-white shadow-card ${className}`}>{children}</section>; }
const Button = ({children,onClick,light=false}:{children:React.ReactNode;onClick?:()=>void;light?:boolean}) => <button onClick={onClick} className={`min-h-11 rounded-control px-4 text-sm font-black ${light?'border border-line bg-white':'bg-[#18241f] text-white'}`}>{children}</button>;

export function PaymentsWorkflow() {
  const [selected,setSelected]=useState(0); const [resolved,setResolved]=useState<number[]>([]);
  const proofs=[{order:'#1047',name:'Meron Tesfaye',amount:'ETB 920',provider:'Telebirr',ref:'FT26082391',wait:'7 min'},{order:'#1042',name:'Selam Bekele',amount:'ETB 1,250',provider:'CBE Birr',ref:'CBE881204',wait:'12 min'},{order:'#1039',name:'Yared Alemu',amount:'ETB 2,400',provider:'M-PESA',ref:'MP449201',wait:'18 min'}];
  const active=proofs[selected];
  return <><PageTitle label="Cashier · Payments" title="Payment reviews" copy="Verify manual transfers before an order is released to the kitchen." action={<Button>Payment history</Button>}/><div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]">
    <Panel className="divide-y divide-line overflow-hidden">{proofs.map((p,i)=><button key={p.order} onClick={()=>setSelected(i)} className={`w-full p-5 text-left ${selected===i?'bg-orange-50':'hover:bg-muted/50'} ${resolved.includes(i)?'opacity-45':''}`}><div className="flex justify-between"><b>{p.order} · {p.name}</b><span className="text-xs font-black text-amber-700">{resolved.includes(i)?'RESOLVED':p.wait}</span></div><p className="mt-2 text-sm text-ink-muted">{p.provider} · {p.amount}</p></button>)}</Panel>
    <Panel className="p-5 sm:p-7"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-black text-brand">{active.order}</p><h2 className="mt-1 text-2xl font-black">{active.amount}</h2><p className="text-sm text-ink-muted">Submitted by {active.name}</p></div><span className="h-fit rounded-full bg-amber-50 px-3 py-2 text-xs font-black text-amber-800">AWAITING REVIEW</span></div><div className="mt-6 grid min-h-72 place-items-center rounded-2xl border-2 border-dashed border-line bg-[#f8f3e9] p-8 text-center"><div><span className="mx-auto grid size-16 place-items-center rounded-2xl bg-white text-2xl shadow-sm">▧</span><p className="mt-4 font-black">Payment proof screenshot</p><p className="mt-1 text-sm text-ink-muted">{active.provider} · Reference {active.ref}</p><button className="mt-4 text-sm font-black text-brand">Open full image ↗</button></div></div><label className="mt-5 block text-xs font-black text-ink-muted">Cashier note<textarea className="mt-2 min-h-20 w-full rounded-xl border border-line p-3 text-sm" placeholder="Optional verification note"/></label><div className="mt-5 flex flex-wrap gap-3"><button onClick={()=>setResolved(v=>[...v,selected])} className="min-h-12 flex-1 rounded-xl bg-emerald-700 px-5 font-black text-white">Confirm & send to kitchen</button><button className="min-h-12 rounded-xl border border-red-200 px-5 font-black text-red-700">Reject proof</button></div></Panel>
  </div></>;
}

export function TablesWorkflow() {
  const [tab,setTab]=useState('Tables'); const [open,setOpen]=useState<number[]>([2,8]);
  return <><PageTitle label="Dining room" title="Tables & QR sessions" copy="Manage table availability, active bills, and printable ordering codes." action={<Button>+ Add table</Button>}/><div className="mb-5 flex gap-2">{['Tables','QR codes','Sessions'].map(x=><button onClick={()=>setTab(x)} className={`rounded-full px-4 py-2 text-xs font-black ${tab===x?'bg-[#18241f] text-white':'bg-white'}`} key={x}>{x}</button>)}</div>
  {tab==='Tables'?<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({length:12},(_,i)=>i+1).map(n=>{const active=open.includes(n);return <Panel className="p-5" key={n}><div className="flex justify-between"><span className="grid size-11 place-items-center rounded-xl bg-muted font-black">{n}</span><span className={`h-fit rounded-full px-2 py-1 text-[9px] font-black ${active?'bg-amber-50 text-amber-800':'bg-emerald-50 text-emerald-700'}`}>{active?'ACTIVE':'AVAILABLE'}</span></div><h2 className="mt-5 font-black">Table {String(n).padStart(2,'0')}</h2><p className="mt-1 text-sm text-ink-muted">{active?'Session open · ETB 1,840':'Seats 4 · Main floor'}</p><button onClick={()=>setOpen(v=>active?v.filter(x=>x!==n):[...v,n])} className="mt-4 w-full rounded-xl border border-line py-2 text-xs font-black">{active?'View session':'Open session'}</button></Panel>})}</div>:<Panel className="p-6"><div className="grid gap-5 md:grid-cols-[220px_1fr]"><div className="grid aspect-square place-items-center rounded-xl bg-[#18241f] text-7xl text-white">▦</div><div><h2 className="text-xl font-black">Bole Main table codes</h2><p className="mt-2 text-sm leading-6 text-ink-muted">Each code opens a unique dine-in session. Download a print sheet or regenerate a compromised code.</p><div className="mt-5 flex gap-3"><Button>Download print sheet</Button><Button light>Regenerate codes</Button></div></div></div></Panel>}</>;
}

export function TeamWorkflow() {
  const [view,setView]=useState('Team'); const [invite,setInvite]=useState(false);
  const people=[['Abebe Kebede','Owner','All branches','ACTIVE'],['Marta Alemu','Manager','Bole Main','ACTIVE'],['Dawit Tesfaye','Cashier','Bole Main','ACTIVE'],['Hana Bekele','Kitchen staff','Downtown','INVITED']];
  return <><PageTitle label="People & locations" title="Team and branches" copy="Invite staff, assign roles, and restrict managers to the branches they operate." action={<Button onClick={()=>setInvite(true)}>+ Invite member</Button>}/><div className="mb-5 flex gap-2">{['Team','Branches'].map(x=><button onClick={()=>setView(x)} className={`rounded-full px-4 py-2 text-xs font-black ${view===x?'bg-[#18241f] text-white':'bg-white'}`} key={x}>{x}</button>)}</div>
  {view==='Team'?<Panel className="overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead><tr className="text-xs uppercase tracking-wider text-ink-muted">{['Member','Role','Branch access','Status',''].map(x=><th className="px-5 py-4" key={x}>{x}</th>)}</tr></thead><tbody>{people.map(p=><tr className="border-t border-line text-sm" key={p[0]}><td className="px-5 py-5 font-black">{p[0]}</td><td className="px-5 py-5">{p[1]}</td><td className="px-5 py-5 text-ink-muted">{p[2]}</td><td className="px-5 py-5"><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-black text-emerald-700">{p[3]}</span></td><td className="px-5 py-5"><button className="font-black text-brand">Manage</button></td></tr>)}</tbody></table></Panel>:<div className="grid gap-4 md:grid-cols-2">{[['Bole Main','Bole Atlas · 8 tables','12 staff'],['Downtown','Mexico Square · 6 tables','8 staff']].map(b=><Panel className="p-6" key={b[0]}><p className="text-xs font-black text-brand">ACTIVE BRANCH</p><h2 className="mt-2 text-xl font-black">{b[0]}</h2><p className="mt-2 text-sm text-ink-muted">{b[1]} · {b[2]}</p><button className="mt-5 text-sm font-black text-brand">Manage branch →</button></Panel>)}</div>}
  {invite&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/45 p-4"><Panel className="w-full max-w-lg p-6"><div className="flex justify-between"><h2 className="text-xl font-black">Invite team member</h2><button onClick={()=>setInvite(false)}>×</button></div><div className="mt-5 space-y-4"><input className="w-full rounded-xl border border-line p-3" placeholder="Email address"/><select className="control-select"><option>Cashier</option><option>Kitchen staff</option><option>Manager</option></select><select className="control-select"><option>Bole Main</option><option>Downtown</option><option>All branches</option></select><Button onClick={()=>setInvite(false)}>Send invitation</Button></div></Panel></div>}</>;
}

export function ShiftWorkflow() {
  const [closed,setClosed]=useState(false);
  return <><PageTitle label="Cashier" title="Day shift" copy="Started today at 8:00 AM by Dawit Tesfaye." action={<span className={`rounded-full px-4 py-2 text-xs font-black ${closed?'bg-stone-200':'bg-emerald-100 text-emerald-800'}`}>{closed?'CLOSED':'OPEN'}</span>}/><div className="grid gap-4 sm:grid-cols-3">{[['Opening cash','ETB 2,000'],['Cash sales','ETB 8,460'],['Expected drawer','ETB 10,460']].map(x=><Panel className="p-5" key={x[0]}><p className="text-sm font-bold text-ink-muted">{x[0]}</p><p className="mt-3 text-2xl font-black">{x[1]}</p></Panel>)}</div><Panel className="mt-5 p-6"><h2 className="text-lg font-black">Close shift reconciliation</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-xs font-black text-ink-muted">Counted cash<input className="mt-2 w-full rounded-xl border border-line p-3" defaultValue="ETB 10,460"/></label><label className="text-xs font-black text-ink-muted">Closing note<input className="mt-2 w-full rounded-xl border border-line p-3" placeholder="Optional note"/></label></div><button disabled={closed} onClick={()=>setClosed(true)} className="mt-5 rounded-xl bg-red-700 px-5 py-3 text-sm font-black text-white disabled:opacity-40">{closed?'Shift closed':'Close and submit shift'}</button></Panel></>;
}

export function OrderDetailWorkflow() {
  const [split,setSplit]=useState(false); const [status,setStatus]=useState('IN PROGRESS');
  return <><PageTitle label="Order #1048" title="Table 08" copy="Dine-in · Opened 12:31 PM · 3 guests" action={<Link href="/orders" className="text-sm font-black text-brand">← All orders</Link>}/><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Panel className="p-6"><div className="flex justify-between"><h2 className="text-lg font-black">Order items</h2><button className="text-sm font-black text-brand">+ Add item</button></div>{[['Special Tibs',2,'ETB 800'],['Fresh Spris',1,'ETB 130'],['Buna Ceremony',1,'ETB 150']].map(x=><div className="mt-4 flex items-center justify-between border-b border-line pb-4" key={x[0]}><div><b>{x[1]} × {x[0]}</b><p className="text-xs text-ink-muted">No special instructions</p></div><div className="flex items-center gap-4"><b>{x[2]}</b><button>•••</button></div></div>)}<div className="mt-5 flex flex-wrap gap-3"><Button onClick={()=>setSplit(!split)}>{split?'Cancel split':'Split bill'}</Button><Button light>Merge table</Button><Button light>Edit order</Button></div>{split&&<div className="mt-5 rounded-xl bg-muted p-4 text-sm"><b>Split into two bills</b><p className="mt-1 text-ink-muted">Select items, then move them to a new bill.</p></div>}</Panel><Panel className="p-6"><p className="text-xs font-black text-brand">ORDER STATUS</p><h2 className="mt-2 text-2xl font-black">{status}</h2><div className="my-5 h-2 rounded-full bg-muted"><div className="h-full w-2/3 rounded-full bg-brand"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="control-select"><option>CONFIRMED</option><option>IN PROGRESS</option><option>READY</option><option>COMPLETED</option></select><div className="mt-6 border-t border-line pt-5"><div className="flex justify-between text-sm"><span>Subtotal</span><b>ETB 1,080</b></div><div className="mt-2 flex justify-between text-sm"><span>Service</span><b>ETB 54</b></div><div className="mt-4 flex justify-between text-xl font-black"><span>Total</span><span>ETB 1,134</span></div></div></Panel></div></>;
}

export function AccountWorkflow() { return <><PageTitle label="Personal settings" title="Account & notifications" copy="Manage your profile, security, and notification preferences."/><div className="grid gap-5 xl:grid-cols-2"><Panel className="p-6"><h2 className="text-lg font-black">Profile</h2><div className="mt-5 grid gap-4"><input className="rounded-xl border border-line p-3" defaultValue="Abebe Kebede"/><input className="rounded-xl border border-line p-3" defaultValue="owner@demo.com"/><input className="rounded-xl border border-line p-3" defaultValue="+251 911 000 000"/><Button>Save profile</Button></div></Panel><Panel className="p-6"><h2 className="text-lg font-black">Notifications</h2>{['Payment proofs','Low stock alerts','Order delays','Daily summary'].map((x,i)=><label className="flex items-center justify-between border-b border-line py-4 text-sm font-bold" key={x}>{x}<input type="checkbox" defaultChecked={i<3} className="size-5 accent-[#b4532a]"/></label>)}</Panel></div></> }

export function PlatformWorkflow() {
  return <><PageTitle label="RestaurantMS platform" title="Tenant operations" copy="Provision restaurants, manage account status, and control platform-wide access." action={<Button>+ Provision tenant</Button>}/><div className="grid gap-4 sm:grid-cols-3">{[['Active tenants','42','+4 this month'],['Monthly GMV','ETB 18.4M','Across all tenants'],['Needs attention','3','Trials and suspensions']].map(x=><Panel className="p-5" key={x[0]}><p className="text-sm font-bold text-ink-muted">{x[0]}</p><p className="mt-3 text-3xl font-black">{x[1]}</p><p className="mt-2 text-xs text-ink-muted">{x[2]}</p></Panel>)}</div><Panel className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="text-xs uppercase text-ink-muted">{['Restaurant','Plan','Branches','Modules','Status',''].map(x=><th className="px-5 py-4" key={x}>{x}</th>)}</tr></thead><tbody>{[['Buna House','Full service','2','8 / 9','ACTIVE'],['Lucy Café','Essential','1','5 / 9','TRIAL'],['Habesha Grill','Full service','4','9 / 9','ACTIVE'],['Atlas Bistro','Essential','1','4 / 9','SUSPENDED']].map(x=><tr className="border-t border-line text-sm" key={x[0]}>{x.slice(0,4).map(y=><td className="px-5 py-5 font-bold" key={y}>{y}</td>)}<td className="px-5 py-5"><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-black">{x[4]}</span></td><td className="px-5 py-5"><Link href="/platform/features" className="font-black text-brand">Manage →</Link></td></tr>)}</tbody></table></Panel></>;
}

export function StateGallery() { const states=[['Loading','Synchronizing restaurant data…','animate-pulse'],['Empty','No orders match this view.',''],['Error','We could not load this section. Retry safely.',''],['Offline','Changes will sync when connection returns.',''],['Permission denied','Your role cannot access this branch.','']]; return <><PageTitle label="System resilience" title="Application states" copy="Reusable states shown consistently across every role and workflow."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{states.map(x=><Panel className="grid min-h-52 place-items-center p-6 text-center" key={x[0]}><div><span className={`mx-auto grid size-12 place-items-center rounded-full bg-muted text-xl ${x[2]}`}>◇</span><h2 className="mt-4 font-black">{x[0]}</h2><p className="mt-2 text-sm text-ink-muted">{x[1]}</p><button className="mt-4 text-sm font-black text-brand">{x[0]==='Permission denied'?'Go back':'Try again'}</button></div></Panel>)}</div></> }
