export enum PlatformRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum TenantRole {
  OWNER = 'OWNER',
  MANAGER = 'MANAGER',
  CASHIER = 'CASHIER',
  KITCHEN_STAFF = 'KITCHEN_STAFF',
  WAITER = 'WAITER',
}

export enum MembershipStatus {
  INVITED = 'INVITED',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REVOKED = 'REVOKED',
}

export enum OrderType {
  DINE_IN = 'DINE_IN',
  TAKEAWAY = 'TAKEAWAY',
  PICKUP = 'PICKUP',
  POS = 'POS',
}

export enum OrderStatus {
  DRAFT = 'DRAFT',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PENDING_CONFIRMATION = 'PENDING_CONFIRMATION',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  READY = 'READY',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  VOIDED = 'VOIDED',
}

export enum PaymentMethod {
  CASH = 'CASH',
  BANK_TRANSFER = 'BANK_TRANSFER',
  TELEBIRR = 'TELEBIRR',
  MANUAL_TRANSFER = 'MANUAL_TRANSFER',
  GATEWAY = 'GATEWAY',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  CANCELLED = 'CANCELLED',
}

export enum TicketStatus {
  QUEUED = 'QUEUED',
  IN_PROGRESS = 'IN_PROGRESS',
  READY = 'READY',
  COMPLETED = 'COMPLETED',
  RECALLED = 'RECALLED',
  CANCELLED = 'CANCELLED',
}

export enum InventoryMovementType {
  RECEIVE = 'RECEIVE',
  DEDUCT = 'DEDUCT',
  ADJUST = 'ADJUST',
  VOID_RESTORE = 'VOID_RESTORE',
  WASTE = 'WASTE',
  TRANSFER = 'TRANSFER',
}

export enum FeatureKey {
  TABLE_QR_ORDERING = 'TABLE_QR_ORDERING',
  PICKUP_ORDERING = 'PICKUP_ORDERING',
  MANUAL_TRANSFER_PAYMENTS = 'MANUAL_TRANSFER_PAYMENTS',
  PAYMENT_GATEWAY = 'PAYMENT_GATEWAY',
  KDS = 'KDS',
  INVENTORY = 'INVENTORY',
  BATCH_INVENTORY = 'BATCH_INVENTORY',
  ANALYTICS = 'ANALYTICS',
  MULTI_BRANCH = 'MULTI_BRANCH',
}

export enum EntitlementStatus {
  ENABLED = 'ENABLED',
  DISABLED = 'DISABLED',
  TRIAL = 'TRIAL',
  SUSPENDED = 'SUSPENDED',
}

export enum BranchFeatureOverride {
  INHERIT = 'INHERIT',
  ENABLED = 'ENABLED',
  DISABLED = 'DISABLED',
}

export enum PaymentPolicy {
  PREPAY_REQUIRED = 'PREPAY_REQUIRED',
  PAY_LATER_ALLOWED = 'PAY_LATER_ALLOWED',
  STAFF_CONFIRMATION_REQUIRED = 'STAFF_CONFIRMATION_REQUIRED',
}

export enum RoundingMode {
  HALF_UP = 'HALF_UP',
  DOWN = 'DOWN',
}

export enum DiningSessionStatus {
  OPEN = 'OPEN',
  CLEARED = 'CLEARED',
}

export enum CashShiftStatus {
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
}

export enum BusinessDayCloseStatus {
  CLOSED = 'CLOSED',
  REOPENED = 'REOPENED',
}

export enum SupportSessionStatus {
  ACTIVE = 'ACTIVE',
  ENDED = 'ENDED',
  EXPIRED = 'EXPIRED',
}

export enum FulfillmentStatus {
  NOT_ROUTED = 'NOT_ROUTED',
  QUEUED = 'QUEUED',
  PREPARING = 'PREPARING',
  PARTIALLY_READY = 'PARTIALLY_READY',
  READY_FOR_EXPO = 'READY_FOR_EXPO',
  READY_FOR_SERVICE = 'READY_FOR_SERVICE',
  PARTIALLY_SERVED = 'PARTIALLY_SERVED',
  SERVED = 'SERVED',
  CANCELLED = 'CANCELLED',
}

export enum TicketType {
  PREPARATION = 'PREPARATION',
  EXPO = 'EXPO',
}

export enum RouteType {
  PREPARE = 'PREPARE',
  ASSEMBLE = 'ASSEMBLE',
}

export enum ServiceMode {
  ALL_AT_ONCE = 'ALL_AT_ONCE',
  PARTIAL_ALLOWED = 'PARTIAL_ALLOWED',
}

export enum ExpoMode {
  NONE = 'NONE',
  OPTIONAL = 'OPTIONAL',
  REQUIRED = 'REQUIRED',
}

export enum ServiceNotificationType {
  STATION_READY = 'STATION_READY',
  ORDER_READY = 'ORDER_READY',
  EXPO_RELEASED = 'EXPO_RELEASED',
  RECALL = 'RECALL',
  REASSIGNED = 'REASSIGNED',
  ESCALATION = 'ESCALATION',
}

export enum ServiceNotificationStatus {
  UNREAD = 'UNREAD',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  RESOLVED = 'RESOLVED',
  CANCELLED = 'CANCELLED',
}

export enum OrderAcceptancePolicy {
  AUTO_AFTER_PAYMENT = 'AUTO_AFTER_PAYMENT',
  CASHIER_CONFIRMATION = 'CASHIER_CONFIRMATION',
  WAITER_APPROVAL = 'WAITER_APPROVAL',
}

export enum OrderAcceptanceChannel {
  ONLINE_PAYMENT = 'ONLINE_PAYMENT',
  CASHIER = 'CASHIER',
  WAITER = 'WAITER',
}

export enum ServiceRequestType {
  CALL_WAITER = 'CALL_WAITER',
  REQUEST_BILL = 'REQUEST_BILL',
  OTHER_ASSISTANCE = 'OTHER_ASSISTANCE',
}

export enum ServiceRequestStatus {
  OPEN = 'OPEN',
  CLAIMED = 'CLAIMED',
  RESOLVED = 'RESOLVED',
  CANCELLED = 'CANCELLED',
  ESCALATED = 'ESCALATED',
}

export enum CancellationDisposition {
  RESTOCK = 'RESTOCK',
  WASTE = 'WASTE',
  NO_ADJUSTMENT = 'NO_ADJUSTMENT',
}

export const PUBLIC_CONTEXT_ERRORS = {
  PUBLIC_CONTEXT_ORDER_TYPE_DENIED: 'PUBLIC_CONTEXT_ORDER_TYPE_DENIED',
  PUBLIC_CONTEXT_PAYMENT_METHOD_DENIED: 'PUBLIC_CONTEXT_PAYMENT_METHOD_DENIED',
  TABLE_SESSION_NOT_CLEARABLE: 'TABLE_SESSION_NOT_CLEARABLE',
} as const;

export const CURRENCY = 'ETB' as const;
export const DEFAULT_TIMEZONE = 'Africa/Addis_Ababa' as const;

export const KITCHEN_ROUTING_ERRORS = {
  MENU_ITEM_ROUTE_MISSING: 'MENU_ITEM_ROUTE_MISSING',
  ROUTE_STATION_INACTIVE: 'ROUTE_STATION_INACTIVE',
  ROUTE_BRANCH_MISMATCH: 'ROUTE_BRANCH_MISMATCH',
  KITCHEN_BRANCH_MISMATCH: 'KITCHEN_BRANCH_MISMATCH',
} as const;

export const KITCHEN_FULFILLMENT_ERRORS = {
  TICKET_VERSION_CONFLICT: 'TICKET_VERSION_CONFLICT',
  ORDER_VERSION_CONFLICT: 'ORDER_VERSION_CONFLICT',
  ORDER_NOT_READY_FOR_COLLECTION: 'ORDER_NOT_READY_FOR_COLLECTION',
  ORDER_NOT_READY_FOR_SERVICE: 'ORDER_NOT_READY_FOR_SERVICE',
  ORDER_ALREADY_COLLECTED: 'ORDER_ALREADY_COLLECTED',
  ORDER_NOT_SERVED: 'ORDER_NOT_SERVED',
  ORDER_ALREADY_SERVED: 'ORDER_ALREADY_SERVED',
  EXPO_RELEASE_BLOCKED: 'EXPO_RELEASE_BLOCKED',
  EXPO_ALREADY_RELEASED: 'EXPO_ALREADY_RELEASED',
  EXPO_RECALL_BLOCKED: 'EXPO_RECALL_BLOCKED',
  WAITER_ASSIGNMENT_DENIED: 'WAITER_ASSIGNMENT_DENIED',
  WAITER_SELF_CLAIM_DISABLED: 'WAITER_SELF_CLAIM_DISABLED',
  ORDER_ALREADY_ASSIGNED: 'ORDER_ALREADY_ASSIGNED',
  INVALID_SERVE_QUANTITIES: 'INVALID_SERVE_QUANTITIES',
  SERVICE_MODE_BLOCKED: 'SERVICE_MODE_BLOCKED',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  DEVICE_TOKEN_INVALID: 'DEVICE_TOKEN_INVALID',
} as const;

export type LocaleCode = 'en' | 'am' | 'ar';
export const LOCALE_CODES: LocaleCode[] = ['en', 'am', 'ar'];
export const DEFAULT_LOCALE: LocaleCode = 'en';
export const RTL_LOCALES: LocaleCode[] = ['ar'];
