export enum PlatformRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum TenantRole {
  OWNER = 'OWNER',
  MANAGER = 'MANAGER',
  CASHIER = 'CASHIER',
  KITCHEN_STAFF = 'KITCHEN_STAFF',
}

export enum MembershipStatus {
  INVITED = 'INVITED',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REVOKED = 'REVOKED',
}

export enum OrderType {
  DINE_IN = 'DINE_IN',
  PICKUP = 'PICKUP',
  POS = 'POS',
}

export enum OrderStatus {
  DRAFT = 'DRAFT',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PENDING_CONFIRMATION = 'PENDING_CONFIRMATION',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  READY = 'READY',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  VOIDED = 'VOIDED',
}

export enum PaymentMethod {
  CASH = 'CASH',
  MANUAL_TRANSFER = 'MANUAL_TRANSFER',
  GATEWAY = 'GATEWAY',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  CANCELLED = 'CANCELLED',
}

export enum TicketStatus {
  QUEUED = 'QUEUED',
  IN_PROGRESS = 'IN_PROGRESS',
  READY = 'READY',
  COMPLETED = 'COMPLETED',
  RECALLED = 'RECALLED',
  CANCELLED = 'CANCELLED',
}

export enum InventoryMovementType {
  RECEIVE = 'RECEIVE',
  DEDUCT = 'DEDUCT',
  ADJUST = 'ADJUST',
  VOID_RESTORE = 'VOID_RESTORE',
  WASTE = 'WASTE',
  TRANSFER = 'TRANSFER',
}

export enum FeatureKey {
  TABLE_QR_ORDERING = 'TABLE_QR_ORDERING',
  PICKUP_ORDERING = 'PICKUP_ORDERING',
  MANUAL_TRANSFER_PAYMENTS = 'MANUAL_TRANSFER_PAYMENTS',
  PAYMENT_GATEWAY = 'PAYMENT_GATEWAY',
  KDS = 'KDS',
  INVENTORY = 'INVENTORY',
  BATCH_INVENTORY = 'BATCH_INVENTORY',
  ANALYTICS = 'ANALYTICS',
  MULTI_BRANCH = 'MULTI_BRANCH',
}

export enum EntitlementStatus {
  ENABLED = 'ENABLED',
  DISABLED = 'DISABLED',
  TRIAL = 'TRIAL',
  SUSPENDED = 'SUSPENDED',
}

export enum BranchFeatureOverride {
  INHERIT = 'INHERIT',
  ENABLED = 'ENABLED',
  DISABLED = 'DISABLED',
}

export enum PaymentPolicy {
  PREPAY_REQUIRED = 'PREPAY_REQUIRED',
  PAY_LATER_ALLOWED = 'PAY_LATER_ALLOWED',
  STAFF_CONFIRMATION_REQUIRED = 'STAFF_CONFIRMATION_REQUIRED',
}

export const CURRENCY = 'ETB' as const;
export const DEFAULT_TIMEZONE = 'Africa/Addis_Ababa' as const;
