include classpath("application.conf")

node-address {
  protocol = http
  host = localhost
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = relaxed
}

queues {
  rms-main {
    defaultVisibilityTimeout = 300 seconds
    receiveMessageWait = 0 seconds
    deadLettersQueue {
      name = "rms-main-dlq"
      maxReceiveCount = 3
    }
  }
  rms-main-dlq {
    defaultVisibilityTimeout = 300 seconds
    receiveMessageWait = 0 seconds
  }
}
